### ISSUE TITLE
The "src\casestudy\CollectHandler.java" need import "global.StaticData.java" and "core.ExceptionHandler.java"

### ISSUE THREAD

**Issue by CaoTianze** [masud-technope/SurfExamples#1]
I try to run your SurfExample Web serviec which download from your homepage in GitHub.But there some error occur in the "src\casestudy\CollectHandler.java".The file need import "global.StaticData.java" and "core.ExceptionHandler.java" ,but it dosn't exist in your repository of SurfExample.
    I was wondering if you would be kind enough to give me some suggestion about your software.

**Comment by masud-technope** [comment]
I uploaded the latest version of SurfExamples. Please let me know if you face any problem in compiling.

**Comment by CaoTianze** [comment]
Oh,thank you. I have compiled the latest version of your software. I am trying to use your software.
